services:
  web:
    build:
      context: .
      args:
        - DJANGO_ENV=production
    command: gunicorn hms_config.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - .env
  worker:
    build: .
    command: celery -A hms_config worker -l info
    env_file:
      - .env
  beat:
    build: .
    command: celery -A hms_config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env

volumes:
  static_volume: