# Generated by Django 5.2.3 on 2025-06-18 20:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('clinical', '0006_admission'),
        ('operations', '0006_bed'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_charging_cycle', models.CharField(choices=[('24_HOUR_CYCLE', '24-Hour Cycle (from admission time)'), ('CALENDAR_DAY', 'Calendar Day (midnight to midnight)')], max_length=20)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized'), ('PAID', 'Paid')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='operations.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clinical.patient')),
            ],
        ),
        migrations.AddField(
            model_name='charge',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='billing.invoice'),
        ),
    ]
