# Generated by Django 5.2.3 on 2025-06-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billingconfiguration_invoice_charge_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='price_at_charge',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
