# Generated by Django 5.2.3 on 2025-06-17 15:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0004_userinvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='operations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicationStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='The current number of units in stock.')),
                ('reorder_level', models.PositiveIntegerField(default=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_stocks', to='operations.branch')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='inventory.medication')),
            ],
        ),
        migrations.AddConstraint(
            model_name='medication',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_medication_for_organization'),
        ),
        migrations.AddConstraint(
            model_name='medicationstock',
            constraint=models.UniqueConstraint(fields=('medication', 'branch'), name='unique_stock_item_per_branch'),
        ),
    ]
