# Generated by Django 5.2.3 on 2025-06-18 17:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_leaverequest_staffavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('building', models.CharField(blank=True, help_text='e.g., Main Building, Wing A', max_length=100)),
                ('floor_number', models.IntegerField(blank=True, null=True)),
                ('block_number', models.CharField(blank=True, help_text='e.g., Block C', max_length=50)),
                ('number', models.CharField(help_text="The bed number or name, e.g., '101-A'", max_length=20)),
                ('category', models.CharField(choices=[('GENERAL_WARD', 'General Ward'), ('SEMI_PRIVATE', 'Semi-Private Room'), ('PRIVATE_ROOM', 'Private Room'), ('ICU', 'Intensive Care Unit')], max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Maintenance')], db_index=True, default='AVAILABLE', max_length=20)),
                ('daily_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='operations.branch')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('branch', 'building', 'floor_number', 'block_number', 'number'), name='unique_bed_location_in_branch')],
            },
        ),
    ]
